#### marker alignment
setwd("~/OneDrive - University of Georgia/Bermudagrass/Comparative_Genomics")
# read sam file generated by Bowtie, aligning HapMap fasta to Sorghum
mySam <- readLines("Zoysia_output.sam")
mySam <- mySam[-(1:22)] # get rid of header rows

# find which rows have successful alignments
aligned <- c(grep("Zjn_chr",mySam))
length(aligned)  # 51334
mySam[aligned[1:20]]


# convert into table
temp <- strsplit(mySam[aligned], "\t")
postable <- data.frame(marker=sapply(temp,
                                     function(x) x[1]),
                       reference=sapply(temp, function(x) x[3]),
                       position=as.integer(sapply(temp, function(x) x[4])))
dim(postable)
postable[1:20,]
write.csv(postable, "Aligned 51334 tags on Z. japonica genome.csv", row.names = FALSE)
