#### marker alignment
setwd("~/OneDrive - University of Georgia/Bermudagrass/Comparative_Genomics")
# read sam file generated by Bowtie, aligning HapMap fasta to Sorghum
mySam <- readLines("Sitalica_output.sam")
mySam <- mySam[-(1:315)] # get rid of header rows

# find which rows have successful alignments
aligned <- c(grep("scaffold",mySam))
length(aligned)  # 36168
mySam[aligned[1:20]]
alignedC <- grep("scaffold",mySam)
length(alignedC) # 36168

# convert into table
temp <- strsplit(mySam[alignedC], "\t")
postable <- data.frame(marker=sapply(temp,
                                     function(x) x[1]),
                       reference=sapply(temp, function(x) x[3]),
                       position=as.integer(sapply(temp, function(x) x[4])))
dim(postable)
postable[1:20,]
write.csv(postable, "Aligned 36168 tags on Sitalica genome.csv", row.names = FALSE)
